# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: my-to-do-app
hooks:
  preup:
    shell: pwsh
    run: ./scripts/preup.ps1
    interactive: true
  postup:
    shell: pwsh
    run: ./scripts/postup.ps1
    interactive: true
  postprovision:
    shell: pwsh
    run: ./scripts/configure-database.ps1
    interactive: true
  postdown:
    shell: pwsh
    run: ./scripts/postdown.ps1
    interactive: true
services:
    my-to-do-app:
        project: .
        host: containerapp
        language: python
        docker:
            path: dockerfile
            remoteBuild: true
        hooks:
            postdeploy:
              shell: pwsh
              run: ./scripts/update-app.ps1
              interactive: true
    my-to-do-api:
        project: ./api
        host: containerapp
        language: python
        docker:
            path: dockerfile
            remoteBuild: true
            build:
                args:
                    USE_AUTH: "true"
infra:
  provider: bicep
  path: ./infra