FROM mcr.microsoft.com/dotnet/sdk:8.0-cbl-mariner2.0 AS build

WORKDIR /config

RUN dotnet new tool-manifest

RUN dotnet tool install Microsoft.DataApiBuilder

RUN dotnet tool run dab -- init --auth.provider "AzureAD" --auth.audience "@env('APPLICATION_ID')" --auth.issuer "@env('ISSUER')" --database-type "mssql" --connection-string "@env('DATABASE_CONNECTION_STRING')"

RUN dotnet tool run dab -- add todo --source "dbo.todo" --permissions "[authenticated]:*"

FROM mcr.microsoft.com/azure-databases/data-api-builder

COPY --from=build /config /App
