name: Build and Push Docker Image to ACR

on: 
  push:
  workflow_dispatch:

env:
  REPO_NAME: mytodoapp
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Random image tag
      run: | 
      
          echo 'TAG='$(uuidgen) | sed 's/-//g' | cut -c 1-17 >> $GITHUB_ENV     

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to ACR
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.ACR_NAME }}/${{ env.REPO_NAME }}:${{ env.TAG }}
        file: Dockerfile
