name: Deploy Azure Container App Revision
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
    workflow_run:
      workflows: [Build and Push Docker Image to ACR]
      types:
        - completed
    workflow_dispatch:

env:
  BICEP_ROOT_PATH: infra/modules/
  DEPLOYMENT_LOCATION: eastus
  RESOURCE_GROUP: My-ToDo-App
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  deploy-Bicep:
    runs-on: ubuntu-latest
    name: 'Deploy ACA Revision'

    steps:

    - name: Azure Login
      uses: Azure/login@v1
      if: ${{ env.AZURE_CLIENT_ID != '' && env.AZURE_TENANT_ID != '' && env.AZURE_SUBSCRIPTION_ID != ''}}
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        
    - name: Checkout IaC Templates
      uses: actions/checkout@main

    - name: Create Random Name for Revision
      run: | 
      
          echo 'REVISION='$(uuidgen) | sed 's/-//g' | cut -c 1-17 >> $GITHUB_ENV

    - name: Deploy ACA Revision
      if: ${{ env.AZURE_SUBSCRIPTION_ID != '' }}
      uses: azure/arm-deploy@v1
      with:
        deploymentName: 'Deploy-ACA-Revision-${{ env.REVISION }}'
        scope: subscription
        region: ${{ env.DEPLOYMENT_LOCATION }}
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: ${{ env.BICEP_ROOT_PATH }}aca-revision.bicep
        parameters: revisionSuffix=${{ env.REVISION }}
        failOnStdErr: true

    - name: Logout of Azure
      run: |
        az logout
