name: Deploy Azure Container App Revision
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
    workflow_run:
      workflows: [Build and Push Docker Image to ACR]
      types:
        - completed
    workflow_dispatch:

env:
  BICEP_ROOT_PATH: infra/modules/
  DEPLOYMENT_LOCATION: eastus
  RESOURCE_GROUP: My-ToDo-App
  REPO_NAME: mytodoapp
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  deploy-Bicep:
    runs-on: ubuntu-latest
    name: 'Deploy ACA Revision'

    steps:

    - name: Azure Login
      uses: Azure/login@v1
      if: ${{ env.AZURE_CLIENT_ID != '' && env.AZURE_TENANT_ID != '' && env.AZURE_SUBSCRIPTION_ID != ''}}
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
    
    - name: Find Existing Azure Resources
      uses: Azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          
          ACR_NAME="$(az acr list --resource-group ${{ env.RESOURCE_GROUP }} --query [0].name -o tsv)"
          echo 'ACR_NAME='$ACR_NAME >> $GITHUB_ENV
          TAG="$(az acr repository show-tags --name $ACR_NAME --repository ${{ env.REPO_NAME }} --orderby time_desc --top 1 -o tsv)"
          echo 'TAG='$TAG >> $GITHUB_ENV
          ACA_NAME="$(az containerapp list --resource-group ${{ env.RESOURCE_GROUP }} --query "[].{Name:name}" -o tsv)"
          echo 'ACA_NAME='$ACA_NAME >> $GITHUB_ENV
            
    - name: Checkout IaC Templates
      uses: actions/checkout@main

    - name: Deploy ACA Revision
      if: ${{ env.ACA_NAME != '' }}
      uses: azure/arm-deploy@v1
      with:
        deploymentName: 'Deploy-ACA-Revision-${{ env.TAG }}'
        scope: resourcegroup
        region: ${{ env.DEPLOYMENT_LOCATION }}
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: ${{ env.BICEP_ROOT_PATH }}aca-revision.bicep
        parameters: revisionSuffix=${{ env.TAG }} acaName=${{ env.ACA_NAME }} imageNameAndVersion=${{ env.REPO_NAME }}:${{ env.TAG }}
        failOnStdErr: true

    - name: Logout of Azure
      run: |
        az logout
